### ISSUE TITLE
tech.v2.tensor column parse/cast error?

### ISSUE THREAD

**Issue by keesterbrugge** [techascent/tech.ml.dataset#30]
Hi,
Thx for this library! I'm using it for data-science in clojure and am experimenting with `pymc3` and `libpython-clj` :) 

I think I've stumbled upon a bug. 
I read that `:object` type columns are implemented now. This works great when I use vectors as the values of a column, however when I try to use `tech.v2.tensor` as the values of a column it get an error. Is something going wrong with parsing? 

Reproducible example:
```clj
;; works
(ds/->dataset [{:a [0.4935 0.5552]} {:a [0.4935 0.5552]}])
;; => _unnamed [2 1]:
;; |              :a |
;; |-----------------|
;; | [0.4935 0.5552] |
;; | [0.4935 0.5552] |

;; doesn't work
(ds/->dataset [{:a (tech.v2.tensor/->tensor [0.4935 0.5552]) }
               {:a (tech.v2.tensor/->tensor [0.4935 0.5552]) }])
;; Execution error (ClassCastException) at tech.ml.dataset.parse.mapseq$map$reify$reify$reify__52074/doubleValue (mapseq.clj:39).
;; tech.v2.tensor.impl.Tensor cannot be cast to java.lang.Number
```

I'm using newest versions of `libpython-clj` and `datatype`
```
{:deps {
        clj-python/libpython-clj {:mvn/version "1.38" }
        techascent/tech.ml.dataset {:mvn/version "2.0-beta-11"}
        techascent/tech.datatype {:mvn/version "5.0-beta-2"}}}
```

**Comment by cnuernber** [comment]
@keesterbrugge - this should work; thanks for the issue.  The confusion is because I am using the spreadsheet parsing system for mapseqs and spreadsheets always have scalars.  I will look into this soon.

**Comment by cnuernber** [comment]
it may work to put the tensors into map: `{:tensor tens-data}`
```clojure

user> (require '[tech.ml.dataset :as ds])
nil
user> (require '[tech.v2.tensor :as dtt])
nil
user> (ds/->dataset [{:a {:tensor (dtt/->tensor [0.4935 0.5552])}}
                     {:a {:tensor (dtt/->tensor [2 4])}}])
_unnamed [2 1]:

|                                                    :a |
|-------------------------------------------------------|
| {:tensor #tech.v2.tensor<float64>[2]
[0.4935 0.5552]} |
|   {:tensor #tech.v2.tensor<float64>[2]
[2.000 4.000]} |
```

I think you would have the same problem with double-array or anything that participates in the tech.datatype system as a first class entity.  Persistent vectors have :object datatypes:
```clojure
 (tech.v2.datatype/get-datatype [1 2])
```

So that worked as nothing expected them to be anything interpretable.  Tensors like above have :float64 datatype and this causes some confusion.  In any case, this is a very useful issue.

**Comment by keesterbrugge** [comment]
Hi @cnuernber,
thx for the fast response. 

The following also gives an error, perhaps for the same reason. 
```clj
;; works
(ds/name-values-seq->dataset {:a [0 1] :ary [[1 2 3] [4 5 6]]}) 
;; _unnamed [2 2]:
;; |    :a |    :ary |
;; |-------+---------|
;; | 0.000 | [1 2 3] |
;; | 1.000 | [4 5 6] |


;; doesn't work
(ds/name-values-seq->dataset {:a [0 1] :ary (tech.v2.tensor/->tensor [[1 2 3] [4 5 6]])})
;; => Execution error (ExceptionInfo) at tech.ml.dataset.impl.dataset/name-values-seq->dataset ;; (dataset.clj:211).
;; Different sized columns detected: clojure.lang.LazySeq@405
```
Thx for the tip for putting the tensor in a map, but for now I'll stick to putting it in a persistent vector such that I can iterate over the rows as follows 

```clj
(ds/->flyweight (ds/name-values-seq->dataset {:a [0 1] :ary [[1 2 3] [4 5 6]]}))
;; => ({:a 0.0, :ary [1 2 3]} {:a 1.0, :ary [4 5 6]})
```

**Comment by cnuernber** [comment]
Yep, that will work.  
This is fixed as of today:
https://github.com/techascent/tech.ml.dataset/blob/master/test/tech/ml/dataset/mapseq_test.clj#L303

**Comment by keesterbrugge** [comment]
Hi @cnuernber,

I see that you've closed the issue but the last code example I gave still doesn't work for me. Perhaps I should've opened a new issue for it since it concerns `name-values-seq->dataset` instead of `->dataset`. But what I expected was that 
```clj
(require '[tech.ml.dataset :as ds])
(= (ds/->dataset [{:a 0 :tensor (tech.v2.tensor/->tensor [1 2 3])}
                  {:a 1 :tensor (tech.v2.tensor/->tensor [4 5 6])}])

   (ds/name-values-seq->dataset {:a [0 1]
                                 :tensor (tech.v2.tensor/->tensor [[1 2 3]
                                                                   [4 5 6]])}))
```
Is this not supported? 
I get back the following error 
```
Execution error (ExceptionInfo) at tech.ml.dataset.impl.dataset/name-values-seq->dataset (dataset.clj:211).
Different sized columns detected: clojure.lang.LazySeq@405
```

**Comment by keesterbrugge** [comment]
Answer to above question is given here https://github.com/techascent/tech.ml.dataset/issues/31
